Feature/Conversion api testing reworke
ONLYOFFICE-QA/convert-service-testing pull request #1038
Opened 2023-06-08 13:49 UTC by l8556

2024-02-09 13:17 UTC, askonev commented
Please fill out the changelog for the changes made, it means the new version

2024-02-09 13:18 UTC, askonev requested changes

2024-02-09 13:18 UTC, askonev commented on assets/exception_file.json
> +
if you have a fixed number of files, then the exclusion mechanism is redundant. I suggest depricking him.

2024-02-28 16:09 UTC, askonev approved these changes
Yes, it looks very cool, good job

2024-02-28 18:39 UTC, alinasafonova approved these changes

2024-03-04 12:37 UTC, merged