Add timer in console for start service
ONLYOFFICE-QA/convert-service-testing pull request #67
Opened 2020-12-09 17:48 UTC by askonev

2020-12-10 07:04 UTC, ShockwaveNN reviewed
Not very good at bash programming
Maybe whole `wait_for_documentserver_start.sh` can be implemented on pure ruby?
Something like: `ruby wait_for_documentserver_start.rb` with simple ruby timer?

2020-12-11 12:04 UTC, askonev commented
> Not very good at bash programming
> Maybe whole `wait_for_documentserver_start.sh` can be implemented on pure ruby?
> Something like: `ruby wait_for_documentserver_start.rb` with simple ruby timer?

2020-12-14 10:51 UTC, ShockwaveNN requested changes

2020-12-14 10:51 UTC, ShockwaveNN commented on helpers/wait_for_documentserver_start.rb
> +  while param.positive?
Simpler variant
```
waiting_time.times do |i|
puts("waiting for #{i} seconids")
sleep 1
end
```

I will not extract this to method, it's simple enought in plain text

2020-12-14 11:55 UTC, ShockwaveNN approved these changes

2020-12-14 11:58 UTC, merged